name: textile
description: Dart client for Textile (https://textile.io).
homepage: https://github.com/textileio/dart-textile
repository: https://github.com/textileio/dart-textile
version: '0.0.1'

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  threads_client: ^0.1.6
  async: ^2.2.0
  grpc: ^2.1.3
  protobuf: ^1.0.1
  uuid: ^2.0.4

dev_dependencies:
  test: ^1.6.4
  pedantic: ^1.0.0