name: textile
description: Dart client for Textile (https://textile.io).
homepage: https://github.com/textileio/dart-textile
repository: https://github.com/textileio/dart-textile
version: '0.1.2'

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  threads_client: ^0.1.9
  async: ^2.2.0
  grpc: ^2.1.3
  protobuf: ^1.0.1
  uuid: ^2.0.4
  http: ^0.12.0
  googleapis_auth: ^0.2.11

dev_dependencies:
  test: ^1.6.4
  pedantic: ^1.0.0