name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    services:
      threads:
        image: textile/go-threads:latest
        env:
          THRDS_HOSTADDR: /ip4/0.0.0.0/tcp/4006
          THRDS_SERVICEAPIADDR: /ip4/0.0.0.0/tcp/5006
          THRDS_SERVICEAPIPROXYADDR: /ip4/0.0.0.0/tcp/5007
          THRDS_APIADDR: /ip4/0.0.0.0/tcp/6006
          THRDS_APIPROXYADDR: /ip4/0.0.0.0/tcp/6007
        ports:
        - 127.0.0.1:4006:4006
        - 127.0.0.1:5006:5006
        - 127.0.0.1:5007:5007
        - 127.0.0.1:6006:6006
        - 127.0.0.1:6007:6007
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
            export PATH="$PATH:/usr/lib/dart/bin";
            pub get
    - name: Run tests
      run: |
           export PATH=/usr/lib/dart/bin:$PATH;
           sleep 10; pub run test
      env:
        TXLT_TEST_TOKEN: ${{ secrets.TXLT_TEST_TOKEN }}
        THREADS_HOST: threads
        THREADS_PORT: ${{ job.services.threads.ports[6006] }}
